## Importando librerías

In [1]:
import numpy as np

### Arange

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeros

In [4]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [5]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Linspace

In [6]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Eye

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [8]:
np.random.rand()

0.9382203174722461

In [9]:
np.random.rand(4)

array([0.14793728, 0.87050041, 0.1884591 , 0.1506753 ])

In [10]:
np.random.rand(4,4)

array([[0.04809554, 0.90302904, 0.60160052, 0.73181527],
       [0.58224789, 0.75318255, 0.27563697, 0.38732031],
       [0.4918343 , 0.70864438, 0.21978038, 0.4500385 ],
       [0.23940809, 0.26021884, 0.38365962, 0.59172248]])

In [19]:
np.random.randint(1,15)

4

In [21]:
np.random.randint(1,100,(10,10))

array([[76, 88, 25, 19, 23, 29, 49, 15,  9, 53],
       [ 9, 22, 58, 84,  5, 24, 85, 15,  9, 79],
       [68, 14, 26, 81, 19, 50, 72, 18, 87, 35],
       [75, 47, 29, 96, 68, 56, 60, 21, 22, 18],
       [ 2, 49, 62, 98, 36, 57, 14, 17, 30, 45],
       [30, 10, 74, 40, 61, 20, 50, 66, 67, 25],
       [65, 77, 61, 30, 85, 32, 39,  1, 85, 59],
       [97, 98, 60, 90, 21, 42, 44, 61, 65, 85],
       [49, 19, 66,  6, 14, 48, 72, 54, 16, 72],
       [47, 63, 77, 15, 28, 11, 85, 89, 46, 95]])